package com.payflow.paymentengine.api;

import com.payflow.paymentengine.api.dto.PaymentEngineResponse;
import com.payflow.paymentengine.api.dto.PaymentEngineSummaryResponse;
import com.payflow.paymentengine.domain.PaymentEngineEventStore;
import com.payflow.paymentengine.summary.CompensationSummaryService;
import com.payflow.paymentengine.summary.SummaryUnavailableException;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.UUID;

/**
 * Read-only view onto the payment engine's state machine for the dashboard.
 * This is the only service that knows a payment's live, current state --
 * payment-api's own Payment row is stamped INITIATED at creation and never
 * updated again, since it has no Kafka consumer of its own.
 */
@RestController
@RequestMapping("/api/payment-engine")
@Tag(name = "Payment Engine", description = "Live payment state, folded from the event-sourced transition log")
public class PaymentEngineController {

    private final PaymentEngineEventStore paymentEngineEventStore;
    private final CompensationSummaryService compensationSummaryService;

    public PaymentEngineController(PaymentEngineEventStore paymentEngineEventStore,
                           CompensationSummaryService compensationSummaryService) {
        this.paymentEngineEventStore = paymentEngineEventStore;
        this.compensationSummaryService = compensationSummaryService;
    }

    @Operation(summary = "List all payments", description = "Every payment's current state, most recently updated first.")
    @GetMapping
    public List<PaymentEngineResponse> list() {
        return paymentEngineEventStore.loadAll().stream()
                .map(PaymentEngineResponse::from)
                .toList();
    }

    @Operation(summary = "Get one payment", description = "A payment's live state, replayed from its event log.")
    @GetMapping("/{paymentId}")
    public PaymentEngineResponse get(@PathVariable UUID paymentId) {
        return paymentEngineEventStore.load(paymentId)
                .map(PaymentEngineResponse::from)
                .orElseThrow(() -> new PaymentEngineNotFoundException(paymentId));
    }

    /**
     * On-demand AI incident summary for a COMPENSATED payment -- the LLM
     * explains an already-final transition history, it never decides anything.
     * Generated once and cached; degrades to a deterministic template when
     * the Claude API is unavailable (see CompensationSummaryService).
     */
    @Operation(summary = "Generate an incident summary",
            description = "Plain-English summary of a COMPENSATED payment's transition history, generated by "
                    + "the Claude API (source AI) or a deterministic template when the API is unavailable "
                    + "(source DETERMINISTIC). Cached after the first call. 409 for non-compensated payments.")
    @GetMapping("/{paymentId}/summary")
    public PaymentEngineSummaryResponse summary(@PathVariable UUID paymentId) {
        return PaymentEngineSummaryResponse.from(compensationSummaryService.summarize(paymentId));
    }

    @ExceptionHandler(PaymentEngineNotFoundException.class)
    public ResponseEntity<String> handleNotFound(PaymentEngineNotFoundException e) {
        return ResponseEntity.status(HttpStatus.NOT_FOUND).body(e.getMessage());
    }

    @ExceptionHandler(SummaryUnavailableException.class)
    public ResponseEntity<String> handleSummaryUnavailable(SummaryUnavailableException e) {
        return ResponseEntity
                .status(e.isNotFound() ? HttpStatus.NOT_FOUND : HttpStatus.CONFLICT)
                .body(e.getMessage());
    }
}
